### ISSUE TITLE
docker: opening seccomp profile (flatpak-docker-seccomp.json) failed: open flatpak-docker-seccomp.json: no such file or directory.

### ISSUE THREAD

**Issue by YaLTeR** [nahuelwexd/flatpak-builder-action#1]
Trying out this action, and getting this error.
https://github.com/YaLTeR/OpenAG/runs/561667681?check_suite_focus=true#step:3:6
```yaml
  build-flatpak:
    name: Build under Flatpak
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      uses: nahuelwexd/flatpak-builder-action@gnome-3-36
      with:
        manifest-path: build-aux/flatpak/pro.openag.OpenAG.json
```

**Comment by nahuelwexd** [comment]
Sorry for that. There were some changes that I was making and because they will take a long time I have moved them to a new branch.

About your project, I have noticed that you use CMake as a build system, which is currently not supported by this action and I doubt that one day it will be supported. I'm working in conjunction with another guy to have an "official" action to build Flatpaks working here on GitHub. I suggest you take a look at https://github.com/bilelmoussaoui/flatpak-github-action, in the `wip` branch.

**Comment by YaLTeR** [comment]
> I have noticed that you use CMake as a build system, which is currently not supported by this action

I figured that if my project builds using a simple `flatpak-builder manifest.json`, then it should work with this action. Is this not the case? Why?

**Comment by YaLTeR** [comment]
Oh, I see, it's because you're doing the last build step manually... What's the reason for that? I'm not sure what the extra commands past build/install do, but isn't it possible to just invoke them last without having to override the build step?

**Comment by nahuelwexd** [comment]
The problem is that `flatpak-builder` re-downloads your project, it doesn't use the code that GitHub currently provides you. You use `actions/checkout@v2` to get all the project code and `flatpak-builder` just ignores that and clones the project again from the links you set in the module's sources property.

It wouldn't be much of a problem if it just depended on that, since the download speeds from the GitHub servers are quite high, but when you want to apply this action on a new branch that you just created or a pull request that has reached you, it will become a problem since `flatpak-builder` will not use that code, it will simply re-download the branch that you have specified in the manifest and that's it.

GNOME Builder suffers the same problem, and solves it the same way. Run `flatpak-builder` only for dependency modules, and then run the build commands one by one manually. The advantage that GNOME Builder runs is that it can parse the manifest to identify the build system it have to use (but it fails at some points as it doesn't support YAML manifests).

I would like to be able to implement all of that, but I prefer to bring all the work to the project started by Bilal Elmoussaoui, which started 6 months before this, in addition to being the basis I used for most of the work (generating a Docker environment similar to the one currently provided by GitHub along with argument parser).

**Comment by YaLTeR** [comment]
Right. Well, in my case I just set it to get the source from a `../..` directory, so there's no second download. It's not an intended way of writing the manifests, but in my case I'm not building under flatpak to get a flatpak bundle, just using it as an optional way to get a build toolchain without installing it on the host system.

> GNOME Builder suffers the same problem, and solves it the same way.

I've already hit a few cases of Builder doing things wrong even with a .json manifest. Unfortunate that there's what seems to be a flatpak manifest design issue like this.

**Comment by nahuelwexd** [comment]
Well, for your specific use case, you can do something like this

```yml
build-flatpak:
  name: Build under Flatpak
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
    with:
      submodules: recursive
  - name: Build
    run: |
      docker run --cap-add SYS_ADMIN --cap-add NET_ADMIN --device /dev/fuse \
      --security-opt apparmor:unconfined --security-opt seccomp=unconfined \
      --workdir /github/workspace --rm -v $GITHUB_WORKSPACE:/github/workspace -i \
      --entrypoint sh nahuelwexd/flatpak-docker:freedesktop-19-08 -c \
      "flatpak-builder flatpak_app build-aux/flatpak/pro.openag.OpenAG.json \\
      --install-deps-from=flathub"
```

And it should work as you expected.
